[project]
name = "apuestas-deportivas"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "lxml==5.3.1",
    "pandas==2.2.3",
    "pymongo==4.11.3",
    "requests==2.32.3",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "scipy-stubs~=1.17.1",
    "seleniumbase>=4.39.2",
    "unidecode==1.3.8",
    "xgboost>=3.2.0",
]
