[project]
name = "apuestas-deportivas"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "cloudscraper>=1.2.71",
    "curl-cffi>=0.14.0",
    "lxml==5.3.1",
    "numpy==2.2.4",
    "pandas==2.2.3",
    "playwright>=1.58.0",
    "playwright-stealth>=2.0.2",
    "pymongo==4.11.3",
    "requests==2.32.3",
    "seleniumbase>=4.39.2",
    "unidecode==1.3.8",
]
